"""

Revision ID: 26dc1826ce39
Revises: 37471c203941
Create Date: 2025-11-16 11:11:59.576841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26dc1826ce39'
down_revision: Union[str, Sequence[str], None] = '37471c203941'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('armor', sa.Column('archivate', sa.Boolean(), nullable=False))
    op.add_column('enchantmens', sa.Column('archivate', sa.Boolean(), nullable=False))
    op.add_column('property', sa.Column('archivate', sa.Boolean(), nullable=False))
    op.add_column('property_player', sa.Column('archivate', sa.Boolean(), nullable=False))
    op.add_column('usable', sa.Column('archivate', sa.Boolean(), nullable=False))
    op.add_column('weapon', sa.Column('archivate', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weapon', 'archivate')
    op.drop_column('usable', 'archivate')
    op.drop_column('property_player', 'archivate')
    op.drop_column('property', 'archivate')
    op.drop_column('enchantmens', 'archivate')
    op.drop_column('armor', 'archivate')
    # ### end Alembic commands ###
