"""

Revision ID: 2ff9b81252ea
Revises: a0eb4fbd7848
Create Date: 2025-11-08 11:48:18.075006

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2ff9b81252ea'
down_revision: Union[str, Sequence[str], None] = 'a0eb4fbd7848'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('armor',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('rare', sa.String(length=255), nullable=False),
    sa.Column('defense', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('class',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('enchantmens',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('property',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('hp', sa.Integer(), nullable=False),
    sa.Column('defence', sa.Integer(), nullable=False),
    sa.Column('ManaPull', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('usable',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('weapon',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('rare', sa.String(length=255), nullable=False),
    sa.Column('defense', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('enemy',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('item_uid', sa.UUID(), nullable=False),
    sa.Column('class_uid', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['class_uid'], ['class.uid'], ),
    sa.ForeignKeyConstraint(['item_uid'], ['items.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('items_armor',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('armor_uid', sa.UUID(), nullable=False),
    sa.Column('item_uid', sa.UUID(), nullable=False),
    sa.Column('enchatmens_uid', sa.UUID(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('strength', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['armor_uid'], ['armor.uid'], ),
    sa.ForeignKeyConstraint(['enchatmens_uid'], ['enchantmens.uid'], ),
    sa.ForeignKeyConstraint(['item_uid'], ['items.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('items_weapon',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('weapon_uid', sa.UUID(), nullable=False),
    sa.Column('item_uid', sa.UUID(), nullable=False),
    sa.Column('enchatmens_uid', sa.UUID(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('strength', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['enchatmens_uid'], ['enchantmens.uid'], ),
    sa.ForeignKeyConstraint(['item_uid'], ['items.uid'], ),
    sa.ForeignKeyConstraint(['weapon_uid'], ['weapon.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('nps',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('item_uid', sa.UUID(), nullable=False),
    sa.Column('class_uid', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['class_uid'], ['class.uid'], ),
    sa.ForeignKeyConstraint(['item_uid'], ['items.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('player',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('item_uid', sa.UUID(), nullable=False),
    sa.Column('class_uid', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['class_uid'], ['class.uid'], ),
    sa.ForeignKeyConstraint(['item_uid'], ['items.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('usable_item',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('weapon_uid', sa.UUID(), nullable=False),
    sa.Column('item_uid', sa.UUID(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('rare', sa.String(), nullable=True),
    sa.Column('usable_locate', sa.String(), nullable=True),
    sa.Column('eatable', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['item_uid'], ['items.uid'], ),
    sa.ForeignKeyConstraint(['weapon_uid'], ['usable.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('property_enemy',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('property_uid', sa.UUID(), nullable=False),
    sa.Column('enemy_uid', sa.UUID(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('strength', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['enemy_uid'], ['enemy.uid'], ),
    sa.ForeignKeyConstraint(['property_uid'], ['property.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('property_nps',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('property_uid', sa.UUID(), nullable=False),
    sa.Column('nps_uid_uid', sa.UUID(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('strength', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['nps_uid_uid'], ['nps.uid'], ),
    sa.ForeignKeyConstraint(['property_uid'], ['property.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('property_player',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('property_uid', sa.UUID(), nullable=False),
    sa.Column('player_uid', sa.UUID(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('strength', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_uid'], ['player.uid'], ),
    sa.ForeignKeyConstraint(['property_uid'], ['property.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('property_player')
    op.drop_table('property_nps')
    op.drop_table('property_enemy')
    op.drop_table('usable_item')
    op.drop_table('player')
    op.drop_table('nps')
    op.drop_table('items_weapon')
    op.drop_table('items_armor')
    op.drop_table('enemy')
    op.drop_table('weapon')
    op.drop_table('usable')
    op.drop_table('property')
    op.drop_table('enchantmens')
    op.drop_table('class')
    op.drop_table('armor')
    # ### end Alembic commands ###
