"""

Revision ID: 37471c203941
Revises: d56a41004bfa
Create Date: 2025-11-16 11:08:22.005401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37471c203941'
down_revision: Union[str, Sequence[str], None] = 'd56a41004bfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enemy', sa.Column('archivate', sa.Boolean(), nullable=False))
    op.add_column('items_armor', sa.Column('archivate', sa.Boolean(), nullable=False))
    op.add_column('items_weapon', sa.Column('archivate', sa.Boolean(), nullable=False))
    op.add_column('nps', sa.Column('archivate', sa.Boolean(), nullable=False))
    op.add_column('player', sa.Column('archivate', sa.Boolean(), nullable=False))
    op.add_column('property_enemy', sa.Column('archivate', sa.Boolean(), nullable=False))
    op.add_column('property_nps', sa.Column('archivate', sa.Boolean(), nullable=False))
    op.add_column('usable_item', sa.Column('archivate', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usable_item', 'archivate')
    op.drop_column('property_nps', 'archivate')
    op.drop_column('property_enemy', 'archivate')
    op.drop_column('player', 'archivate')
    op.drop_column('nps', 'archivate')
    op.drop_column('items_weapon', 'archivate')
    op.drop_column('items_armor', 'archivate')
    op.drop_column('enemy', 'archivate')
    # ### end Alembic commands ###
