"""

Revision ID: 9950df9d56e2
Revises: 26dc1826ce39
Create Date: 2025-11-16 11:12:32.365002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9950df9d56e2'
down_revision: Union[str, Sequence[str], None] = '26dc1826ce39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class', sa.Column('archivate', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('class', 'archivate')
    # ### end Alembic commands ###
