"""

Revision ID: cfbb86393d31
Revises: 2ff9b81252ea
Create Date: 2025-11-09 16:10:37.978057

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'cfbb86393d31'
down_revision: Union[str, Sequence[str], None] = '2ff9b81252ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('archivate', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'archivate')
    # ### end Alembic commands ###
